// src/lib/icrc7-actor.ts
//
// Phase 3.6 frontend bridge: parallel raw actor for ICRC-7 / ICRC-37 calls.
//
// Background: the typed Backend wrapper at src/backend.ts is generated by
// @caffeinelabs/bindgen and was last regenerated on 2026-04-30 — it does
// NOT include any of the Phase 3.x ICRC-7 methods. The bindgen tool is
// not installed locally, so we cannot regenerate the wrapper. To unblock
// Phase 3.6 frontend work without hand-editing the generated file, this
// module builds a SEPARATE actor directly from the regenerated Candid
// idlFactory in src/declarations/backend.did.
//
// The two actors share the same identity (via @caffeineai's
// useInternetIdentity) and the same canister id (via loadConfig), so
// auth state and target canister stay in lockstep.
//
// CLEANUP PATH: when @caffeinelabs/bindgen becomes available and
// src/backend.ts is regenerated to include Phase 3.x methods, delete
// this file and switch the four ICRC-7 hooks in useBackend.ts to call
// the typed Backend wrapper instead.

import { loadConfig } from "@caffeineai/core-infrastructure";
import { Actor, type ActorSubclass, HttpAgent } from "@icp-sdk/core/agent";
import { useQuery } from "@tanstack/react-query";
import { type _SERVICE, idlFactory } from "../declarations/backend.did";
import { useAuth } from "../hooks/useAuth";

// Distinct from useActor's "actor" key so the two actors don't collide
// in the React Query cache.
const ICRC7_ACTOR_QUERY_KEY = "icrc7_actor";

export type Icrc7Actor = ActorSubclass<_SERVICE>;

export function useIcrc7Actor(): {
  actor: Icrc7Actor | null;
  isFetching: boolean;
} {
  // useAuth wraps useInternetIdentity and computes isAuthenticated from
  // the identity (handling both v0.1 and v0.2 of core-infrastructure
  // consistently), so we don't depend on a specific InternetIdentityContext
  // shape here.
  const { identity, isAuthenticated } = useAuth();
  const principalText = identity?.getPrincipal().toString();

  const q = useQuery({
    queryKey: [ICRC7_ACTOR_QUERY_KEY, principalText],
    queryFn: async () => {
      try {
        const config = await loadConfig();
        const agentOpts = isAuthenticated && identity ? { identity } : {};
        // Only pass a host when it's a non-empty, non-placeholder value.
        // In Vite proxy mode env.json leaves backend_host empty/undefined,
        // and passing host:"" breaks HttpAgent. When omitted, the agent
        // defaults to window.location.origin and Vite forwards /api → 4943.
        const backendHost =
          config.backend_host &&
          config.backend_host !== "undefined" &&
          config.backend_host !== ""
            ? config.backend_host
            : undefined;
        const agent = new HttpAgent({
          ...agentOpts,
          ...(backendHost ? { host: backendHost } : {}),
        });
        // fetchRootKey is required for the local replica's self-signed cert.
        // Use DFX_NETWORK (exposed by vite-plugin-environment) as the
        // authoritative local-vs-mainnet signal, with a hostname fallback.
        const isLocal =
          process.env.DFX_NETWORK === "local" ||
          !!(backendHost ?? window.location.hostname).match(
            /localhost|127\.0\.0\.1/,
          );
        if (isLocal) {
          await agent.fetchRootKey().catch(() => {});
        }
        return Actor.createActor<_SERVICE>(idlFactory, {
          agent,
          canisterId: config.backend_canister_id,
        });
      } catch (e) {
        console.error("[icrc7-actor] failed to create actor:", e);
        throw e;
      }
    },
    staleTime: Number.POSITIVE_INFINITY,
    enabled: true,
  });

  return { actor: q.data ?? null, isFetching: q.isFetching };
}
