[package]
name = "backend"
version = "0.1.0"

[build]
outputDir = "src/backend/dist"
args = [ "--release" ]

[canisters.backend]
main = "src/backend/main.mo"

[canisters.docs_backend]
main = "src/docs_backend/main.mo"

[canisters.spicy_ai_canister]
main = "src/spicy_ai_canister/main.mo"

[toolchain]
moc = "1.3.0"
lintoko = "0.7.0"

[lint]
extends = true

[moc]
args = [ "--actor-idl=src/backend/system-idl" ]

[dependencies]
core = "2.2.0"
llm = "2.1.0"
ic-certification = "1.1.0"
