/**
 * Carnival midway photo assets — generated by scripts/build-arcade-assets.mjs
 */
import type { GameId } from "../config";

export const ARCADE_ASSETS = {
  midwayBg: "/games/arcade/midway-bg.webp",
  boothSlicer: "/games/arcade/booth-slicer.webp",
  boothPepperPatch: "/games/arcade/booth-pepper-patch.webp",
  boothCrafter: "/games/arcade/booth-crafter.webp",
  ticketStub: "/games/arcade/ticket-stub.webp",
  prizePlaque: "/games/arcade/prize-plaque.webp",
  woodBrassTexture: "/games/arcade/wood-brass-texture.webp",
} as const;

export const ARCADE_BOOTH_BY_GAME: Record<GameId, string> = {
  slicer: ARCADE_ASSETS.boothSlicer,
  "pepper-patch": ARCADE_ASSETS.boothPepperPatch,
  crafter: ARCADE_ASSETS.boothCrafter,
};

/** Accessibility-safe marquee timing (matches leaderboard sign). */
export const ARCADE_BULB_CHASE = {
  stepSec: 1.0,
  cycleSec: 12,
} as const;
